kind: Service
apiVersion: v1
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: pushgateway
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
    nodePort: 30901

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/part_of: "true"
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:v0.5.2
        ports:
        - containerPort: 9091
