{
 "title": "Guestbook",
 "description": "Prometheus dashboard for Guestbook Redis servers",
 "tags": [
  "prometheus",
  "redis",
  "guestbook"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(redis_connected_clients, instance)"
   },
   {
    "name": "addr",
    "query": "label_values(redis_connected_clients, addr)"
   }
  ]
 },
 "panels": [
  { "title": "Redis: Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage (1m avg), Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(rate(process_cpu_seconds_total{role=\"master\"}[1m]) * 100)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sort_desc(rate(process_cpu_seconds_total{role=\"slave\"}[1m]) * 100)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory usage, Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(redis_memory_used_bytes{role=\"slave\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sort_desc(redis_memory_used_bytes{role=\"master\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "bytes Rx (+), Tx (-)" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{role=\"master\"}[1m])",
     "legendFormat": "Rx: {{ kubernetes_pod_name }}"
    },
    {
     "expr": "rate(redis_net_input_bytes_total{role=\"slave\"}[1m])",
     "legendFormat": "Rx: {{ kubernetes_pod_name }}"
    },
    {
     "expr": "- rate(redis_net_output_bytes_total{role=\"master\"}[1m])",
     "legendFormat": "Tx: {{ kubernetes_pod_name }}"
    },
    {
     "expr": "- rate(redis_net_output_bytes_total{role=\"slave\"}[1m])",
     "legendFormat": "Tx: {{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Commands Executed (5m avg), Stacked",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "commands/s" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{role=\"slave\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(redis_commands_processed_total{role=\"master\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Hits / Misses (1m avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "hits(+), misses(-)/s" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{role=\"master\"}[5m])",
     "legendFormat": "Hits: {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(redis_keyspace_hits_total{role=\"slave\"}[1m])",
     "legendFormat": "Hits: {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{role=\"master\"}[5m])",
     "legendFormat": "Misses: {{kubernetes_pod_name}}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{role=\"slave\"}[1m])",
     "legendFormat": "Misses: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Command Calls (1m avg), Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "calls/s" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_command_call_duration_seconds_count[1m]))",
     "legendFormat": "CMD: {{ cmd }} on POD: {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Top 5 Command Call Duration (1m avg), Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, rate(redis_command_call_duration_seconds_sum[1m])))",
     "legendFormat": "CMD: {{ cmd }} on POD: {{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Redis: Per Instance Views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Pod Name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=\"$addr\", instance=\"$instance\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 35 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{addr=\"$addr\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=\"$addr\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Commands Executed (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "commands/s" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{addr=~\"$addr\", instance=\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Hits / Misses (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "hits(+), misses(-)/s" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=\"$addr\", instance=\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=\"$addr\", instance=\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$addr\", instance=\"$instance\"} ",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CPU usage (1m avg), Stacked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc((rate(redis_used_cpu_sys{addr=~\"$addr\", instance=\"$instance\"}[5m]) + rate(redis_used_cpu_user{addr=~\"$addr\", instance=\"$instance\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Network I/O (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bytes Rx (+), Tx (-)" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=\"$addr\", instance=\"$instance\"}[5m])",
     "legendFormat": "Rx"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=\"$addr\", instance=\"$instance\"}[5m])",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Total Items per DB, Stacked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(redis_db_keys{addr=~\"$addr\"}) by (db))",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\", instance=\"$instance\"}) - sum (redis_db_keys_expiring{addr=~\"$addr\", instance=\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$addr\", instance=\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$addr\", instance=\"$instance\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$addr\", instance=\"$instance\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Top 5 Command Calls Stacked (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "calls/s" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_command_call_duration_seconds_count{addr=~\"$addr\", instance=\"$instance\"} [5m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Top 5 Command Call Duration (5m avg), Stacked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "sort_desc(topk(5, rate(redis_command_call_duration_seconds_sum{addr=~\"$addr\", instance=\"$instance\"}[5m])))",
     "legendFormat": "CMD: {{ cmd }} on POD: {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}