{
 "title": "Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods running",
     "type": "singlestat",
     "description": "Total pods running in cluster.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods pending",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_status_phase{phase=\"Pending\"} == 1)"
      }
     ]
    },
    {
     "title": "Container running",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_running)"
      }
     ]
    },
    {
     "title": "Container waiting",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting_reason != 0) "
      }
     ]
    },
    {
     "title": "Replicas available",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kube_deployment_status_replicas_available)"
      }
     ]
    },
    {
     "title": "Replicas unavailable",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_deployment_status_replicas_unavailable) == 1"
      }
     ]
    },
    {
     "title": "Services",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "count(kube_service_created)" }
     ]
    },
    {
     "title": "Deployments",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "count(kube_deployment_created)" }
     ]
    },
    {
     "title": "Pod info",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kube_pod_info{node=~\"$Node\"}"
      }
     ]
    },
    {
     "title": "Service info",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      { "expr": "kube_service_info" }
     ]
    },
    {
     "title": "Container info",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "targets": [
      { "expr": "kube_pod_container_info" }
     ]
    },
    {
     "title": "Node info",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "kube_node_info{node=~\"$Node\"}"
      }
     ]
    }
   ]
  },
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (machine_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster FS utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/[sv]d[a-z][1-9]$\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Swap size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_swap{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id!=\"\", namespace!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_fs_limit_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Network I/O (1m avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Rx: Total"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[1m]))",
     "legendFormat": "Tx: Total"
    }
   ]
  },
  {
   "title": "Memory usage by Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU usage by Namespace (5m avg)",
   "type": "graph",
   "description": "CPU utilization over a given period of time. 100% means one core is fully utilized,",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{id!=\"\", namespace!=\"\"}[5m]) * 100) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Network I/O by Namespace (1m avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace!=\"\", kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (namespace)",
     "legendFormat": "Rx: {{namespace}}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{namespace!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (namespace)",
     "legendFormat": "Tx: {{namespace}}"
    }
   ]
  },
  {
   "title": "Pod usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod CPU usage (1m avg)",
     "type": "graph",
     "description": "Cumulative cpu time consumed per second",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod memory usage",
     "type": "graph",
     "description": "Accumulated current memory usage per pod, including all memory regardless of when it was accessed.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\", pod_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod_name))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod bytes written (5m avg)",
     "type": "graph",
     "description": "Cumulative count of bytes written per pod and device per second.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_fs_writes_bytes_total{name!=\"\", device!=\"\"}[5m])) by (pod_name, device))",
       "legendFormat": "{{pod_name}} on {{device}}"
      }
     ]
    },
    {
     "title": "Pod bytes read (5m avg)",
     "type": "graph",
     "description": "Cumulative count of bytes written per pod and device per second.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(rate(container_fs_reads_bytes_total{name!=\"\", device!=\"\"}[5m])) by (pod_name, device))",
       "legendFormat": "{{pod_name}} from {{device}}"
      }
     ]
    },
    {
     "title": "Pod Network Rx (1m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]) ))",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod Network Tx (1m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (pod_name) (rate (container_network_transmit_bytes_total{name!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[1m]) ) )",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[1m])) by (container_name, pod_name)",
       "legendFormat": "{{ container_name }} | pod: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Container memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\", pod_name!=\"POD\", container_name!=\"POD\"}) by (container_name, pod_name))",
       "legendFormat": "{{container_name}} | pod: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod Network RX (1m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (container_name, pod_name) (rate (container_network_receive_bytes_total{image!=\"\", name!=\"\"}[1m]) ))",
       "legendFormat": "{{ container_name }} | pod: {{ pod_name }}"
      }
     ]
    },
    {
     "title": "Pod Network TX (1m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum by (container_name, pod_name) (rate (container_network_transmit_bytes_total{name!=\"\"}[1m]) ) )",
       "legendFormat": "{{ container_name}}  | pod: {{ pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "SkyDNS Request Count (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "requests/s" }
     ],
     "targets": [
      {
       "expr": "rate(skydns_skydns_dns_request_count_total[5m])",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "SkyDNS Errors Count (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "errors/s" }
     ],
     "targets": [
      {
       "expr": "rate(skydns_skydns_dns_error_count_total[5m])",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "SkyDNS Cache Misses (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "misses/s" }
     ],
     "targets": [
      {
       "expr": "rate(skydns_skydns_dns_cachemiss_count_total[5m])",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "SkyDNS Request Duration (5m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(skydns_skydns_dns_request_duration_seconds_sum[5m])/rate(skydns_skydns_dns_request_duration_seconds_count[5m])"
      }
     ]
    },
    {
     "title": "SkyDNS Response Size (5m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(skydns_skydns_dns_response_size_bytes_sum[5m])"
      }
     ]
    },
    {
     "title": "DNSmasq Hits (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "hits/s" }
     ],
     "targets": [
      { "expr": "rate(kubedns_dnsmasq_hits[5m])" }
     ]
    },
    {
     "title": "DNSmasq Misses (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "misses/s" }
     ],
     "targets": [
      {
       "expr": "rate(kubedns_dnsmasq_misses[5m])"
      }
     ]
    },
    {
     "title": "DNSmasq Errors (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "errors/s" }
     ],
     "targets": [
      {
       "expr": "rate(kubedns_dnsmasq_errors[5m])"
      }
     ]
    },
    {
     "title": "DNSmasq Latency (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(kubedns_probe_dnsmasq_latency_ms_sum[5m]) / rate(kubedns_probe_dnsmasq_latency_ms_count[5m])"
      }
     ]
    }
   ]
  }
 ]
}