{
 "title": "Prometheus Internal Stats",
 "description": "The official, pre-built Prometheus Stats Dashboard, extended a bit by lubovarganike.",
 "tags": [
  "prometheus",
  "kubernetes"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Target Scrapes (last 5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_target_interval_length_seconds_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "content": "<img src=\"http://prometheus.io/assets/prometheus_logo_grey.svg\" alt=\"Prometheus logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">Prometheus</span>\n\n<p style=\"margin-top: 10px;\">You're using Prometheus, an open-source systems monitoring and alerting toolkit originally built at SoundCloud. For more information, check out the <a href=\"http://www.grafana.org/\">Grafana</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects.</p>"
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "content": "#### Samples Ingested\nThis graph displays the count of samples ingested by the Prometheus server, as measured over the last 5 minutes, per time series in the range vector. When troubleshooting an issue on IRC or Github, this is often the first stat requested by the Prometheus team. "
  },
  {
   "title": "Rule Eval Duration",
   "type": "graph",
   "description": "The duration for a rule to execute.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "prometheus_evaluator_duration_seconds{quantile!=\"0.01\", quantile!=\"0.05\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "content": "#### Scrapes\nPrometheus scrapes metrics from instrumented jobs, either directly or via an intermediary push gateway for short-lived jobs. Target scrapes will show how frequently targets are scraped, as measured over the last 5 minutes, per time series in the range vector. Scrape Duration will show how long the scrapes are taking, with percentiles available as series. "
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "content": "#### Rule Evaluation Duration\nThis graph panel plots the duration for all evaluations to execute. The 50th percentile, 90th percentile and 99th percentile are shown as three separate series to help identify outliers that may be skewing the data."
  },
  {
   "title": "Queries to prometheus (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_microseconds_count{handler=~\"prometheus\"}[1m])",
     "legendFormat": "Node: {{kubernetes_io_hostname}}, Job: {{job}}"
    }
   ]
  },
  {
   "title": "Kubernetes events handled (5m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Events/s" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(prometheus_sd_kubernetes_events_total[5m])) by (event, role))",
     "legendFormat": "Event: {{event}} -- Role: {{role}}"
    }
   ]
  }
 ]
}