global:
  smtp_smarthost: 'mailhog.monitoring.svc.cluster.local:1025'
  smtp_from: 'alertmanager@k8s-exxeta.com'
  smtp_require_tls: false
  smtp_hello: 'k8s-alertmanager'
  
# Default route
route:
  group_by: [cluster, alertname, resource, severity]

  # Default receiver
  receiver: test-emails

  # Child routes
  routes:
    
  # Creating a rule for CPU related alerts
  - match_re:
      resource: ^cpu$
    receiver: cpu-mails

    # Sub route for critical CPU alerts
    routes:
    - match:
        severity: critical
      receiver: crit-mails

# Setting different receivers
receivers:
- name: 'test-emails'
  email_configs:
  - to: 'test-emails@example.com'
- name: 'cpu-mails'
  email_configs:
  - to: 'cpu-mails@example.com'
- name: 'crit-mails'
  email_configs:
    - to: 'crit-mails@example.com'